name: particle_packages
publish_to: 'none'

environment:
  sdk: ^3.9.0

workspace:
  - packages/particle_core
  - packages/particle_text
  - packages/particle_image
  - examples/particle_examples

dev_dependencies:
  melos: ^7.4.0

melos:
  repository: https://github.com/HemangSidapara/particle_packages

  command:
    version:
      linkToCommits: true
    clean:
      hooks:
        # Runs "flutter clean" in all Flutter packages (`--flutter`)
        # with a concurrency of 1 at a time (`--concurrency=1`).
        post: melos exec --flutter --concurrency=1 -- "flutter clean"

  scripts:
    get:
      exec: melos bootstrap
    test:
      run: melos exec --flutter --concurrency=1 -- "flutter test"
      packageFilters:
        dirExists: test
    doc:dry:
      run: |
        melos exec --scope="particle_core" -- "dart doc --dry-run"
        melos exec --scope="particle_text" -- "dart doc --dry-run"
        melos exec --scope="particle_image" -- "dart doc --dry-run"
    publish:dry:
      run: |
        melos exec --scope="particle_core" -- "dart pub publish --dry-run"
        melos exec --scope="particle_text" -- "dart pub publish --dry-run"
        melos exec --scope="particle_image" -- "dart pub publish --dry-run"
    publish:
      run: |
        melos exec --scope="particle_core" -- "dart pub publish"
        melos exec --scope="particle_text" -- "dart pub publish"
        melos exec --scope="particle_image" -- "dart pub publish"
