name: particle_core
description: >
  Core engine for particle effects in Flutter. High-performance physics,
  single GPU draw call rendering via drawRawAtlas, and full customization.
version: 0.0.2
homepage: https://github.com/HemangSidapara/particle_packages
repository: https://github.com/HemangSidapara/particle_packages/tree/master/packages/particle_core
issue_tracker: https://github.com/HemangSidapara/particle_packages/issues

topics:
  - particles
  - animation
  - canvas
  - physics
  - effects

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
